maintainer       "ttree ldt"
maintainer_email "dfeyer@ttree.ch"
license          "All rights reserved"
description      "Installs/Configures pootle"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
depends          "apache2"
depends			 "build-essential"
depends			 "git"
depends			 "python"
depends			 "memcached"
depends			 "postfix"
depends			 "mysql"
depends			 "database"